name: ws_flutter
description: An enterprise-class package of Flutter components for mobile applications.
version: 1.0.1
homepage: https://github.com/jasondevelopment/ws_flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.9 #åå¸

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
